package com.sportradar.wc;

public enum CountryEnum {
    SPAIN, BRAZIL, ARGENTINA, AUSTRALIA, GERMANY, FRANCE, MEXICO, CANADA, URUGUAY, ITALY,
    SLOVENIA, CROATIA, USA, BELGIUM, SERBIA, JAPAN, MONTENEGRO
}
